// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeManagement.Infrastructure.Persistence;

#nullable disable

namespace OfficeManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OfficeManagement.Domain.Entities.Department", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Code").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.ToTable("Departments");
            });

            modelBuilder.Entity("OfficeManagement.Domain.Entities.Employee", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<Guid>("DepartmentId").HasColumnType("uniqueidentifier");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Phone").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Position").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Role").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<Guid?>("TableId").HasColumnType("uniqueidentifier");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("DepartmentId");
                b.HasIndex("TableId");
                b.ToTable("Employees");
            });

            modelBuilder.Entity("OfficeManagement.Domain.Entities.OfficeLayout", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.ToTable("OfficeLayouts");
            });

            modelBuilder.Entity("OfficeManagement.Domain.Entities.Room", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<int>("Capacity").HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("Floor").HasColumnType("int");
                b.Property<Guid>("LayoutId").HasColumnType("uniqueidentifier");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("LayoutId");
                b.ToTable("Rooms");
            });

            modelBuilder.Entity("OfficeManagement.Domain.Entities.Table", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<double>("PositionX").HasColumnType("float");
                b.Property<double>("PositionY").HasColumnType("float");
                b.Property<Guid>("RoomId").HasColumnType("uniqueidentifier");
                b.Property<int>("Seats").HasColumnType("int");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("RoomId");
                b.ToTable("Tables");
            });

            modelBuilder.Entity("OfficeManagement.Domain.Entities.Employee", b =>
            {
                b.HasOne("OfficeManagement.Domain.Entities.Department", "Department")
                    .WithMany("Employees").HasForeignKey("DepartmentId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("OfficeManagement.Domain.Entities.Table", "Table")
                    .WithMany("Employees").HasForeignKey("TableId").OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Department");
                b.Navigation("Table");
            });

            modelBuilder.Entity("OfficeManagement.Domain.Entities.Room", b =>
            {
                b.HasOne("OfficeManagement.Domain.Entities.OfficeLayout", "Layout")
                    .WithMany("Rooms").HasForeignKey("LayoutId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Layout");
            });

            modelBuilder.Entity("OfficeManagement.Domain.Entities.Table", b =>
            {
                b.HasOne("OfficeManagement.Domain.Entities.Room", "Room")
                    .WithMany("Tables").HasForeignKey("RoomId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Room");
            });

            modelBuilder.Entity("OfficeManagement.Domain.Entities.Department", b => b.Navigation("Employees"));
            modelBuilder.Entity("OfficeManagement.Domain.Entities.OfficeLayout", b => b.Navigation("Rooms"));
            modelBuilder.Entity("OfficeManagement.Domain.Entities.Room", b => b.Navigation("Tables"));
            modelBuilder.Entity("OfficeManagement.Domain.Entities.Table", b => b.Navigation("Employees"));
#pragma warning restore 612, 618
        }
    }
}
